///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace JiraJenkinsIntegration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JiraJenkinsIntegrationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("b61a4d40-17bc-48d1-b278-c4a496d8d906")]
    public partial class JiraJenkinsIntegrationRepository : RepoGenBaseFolder
    {
        static JiraJenkinsIntegrationRepository instance = new JiraJenkinsIntegrationRepository();

        /// <summary>
        /// Gets the singleton class instance representing the JiraJenkinsIntegrationRepository element repository.
        /// </summary>
        [RepositoryFolder("b61a4d40-17bc-48d1-b278-c4a496d8d906")]
        public static JiraJenkinsIntegrationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JiraJenkinsIntegrationRepository() 
            : base("JiraJenkinsIntegrationRepository", "/", null, 0, false, "b61a4d40-17bc-48d1-b278-c4a496d8d906", ".\\RepositoryImages\\JiraJenkinsIntegrationRepositoryb61a4d40.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b61a4d40-17bc-48d1-b278-c4a496d8d906")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class JiraJenkinsIntegrationRepositoryFolders
    {
    }
#pragma warning restore 0436
}